### ISSUE TITLE
adapt layout to original nabucco app

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/nabucco#2]
e.g. logo(s), fonts, footer
see https://digitalpasts.github.io/nabucco/items/22741

**Comment by pirnr81** [comment]
Addendum: Jursa prefers the style closer to Labasi than the original app. Hence some random stylistic interventions on my part

**Comment by csae8092** [comment]
maybe harmonize image/label size in application header/nav-bar or remove one of the two images

**Comment by pirnr81** [comment]
1) re-style landing/index page and 2) style glossary overview
